### ISSUE TITLE
User Story: Build RHEL 8 discovery-server container (0.9.0 )

### ISSUE THREAD

**Issue by kholdaway** [redhat-discovery/discovery#140]
User Story: Build discovery-server containers for RHEL8

- [x] Step One: Change the signing intent in the container config files to `release`
- [x] Step Two: Have all signed rpms through moving the advisory to the QE state
- [x] Step Three: Add any rpms that we were able to obtain using the `unsigned` signing intent, but are not able to obtain with the `release` method to the errata advisory. Repeat step two.
- [x] Step Four: Officially build container.

**Comment by myersCody** [comment]
In order to get `ansible-runner` into the build environment for the discovery container, I needed to tag it as a `discovery-0.9-rhel-8-canidate` so that we could find it in the: https://errata.devel.redhat.com/advisory/43670/builds

**Steps to tag a build:**
```
[root@vrhel8dev deps]#  brew list-tagged --inherit --latest discovery-0.9-rhel-8-container-build | grep ansible-runner-1 | awk '{ print $1 }'
ansible-runner-1.3.4-2.el8ar
python-lockfile-0.11.0-8.el8ar
[root@vrhel8dev discovery-server-container]# brew tag-build discovery-0.9-rhel-8-candidate ansible-runner-1.3.4-2.el8ar
Created task 22688684
Watching tasks (this may be safely interrupted)...
22688684 tagBuild (noarch): free
22688684 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

22688684 tagBuild (noarch) completed successfully
```

---

However, when I added it to the cli advisory as a temporary work around to allow me to build the container the package failed the RPM Diff. Therefore, I opened a jira ticket to resolve the issue of a missing product list for ansible-runner.

⚠️ **Blocked By JIRA Ticket:** https://projects.engineering.redhat.com/browse/RCM-62483
