### ISSUE TITLE
User Story: Complete the errata process for RHEL 7 discovery 0.9.x CLI

### ISSUE THREAD

**Issue by kholdaway** [redhat-discovery/discovery#34]
Now that we have an official BREW build, complete the errata checklist

git-dist: http://pkgs.devel.redhat.com/cgit/rpms/discovery/
BREW build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=21253964

-------

Advisory: https://errata.devel.redhat.com/advisory/43670/

**Comment by myersCody** [comment]
An advisory was created in bugzilla for discovery

**Comment by myersCody** [comment]
Added builds to Advisory to pass RPMDiffs stage.

**Comment by myersCody** [comment]
RPMDiff resulted in 5/6 builds that were added passing; however, one was marked as `Needs Inspection`.

**Inspection Data:**
```
Symlinks
--
This test shows symlinks that became danglingFor more information about this test see Symlinks documentation.
```
After reading the [Symlinks documentation](https://docs.engineering.redhat.com/display/HTD/rpmdiff-symlinks) I decided that the error could be waved due to:
```
If your symlink points to a file in another package, e.g. a dependency or a system file, rpmdiff cannot detect this. Remember, rpmdiff does not install or even know about package dependencies. That's TPS's job.
```
Therefore, I decided that we could wave this error and did so through the RPMDiff WebUI interface located here:
https://rpmdiff.engineering.redhat.com/run/411190/27/

**Comment by myersCody** [comment]
If we do not get the RHEL7 discovery cli working by GA, we need to transition our errata advisory for RHEL7 CLI from y stream (what it currently is) to z stream. 

We can do this from here: https://errata.devel.redhat.com/errata/new_errata

Click: `Clone and advisory` and put the advisory number in there.
